listener 18883
protocol mqtt
allow_anonymous true
cafile /home/saniyachavani/Documents/PrecisionpulseDocs/dspl-precision-pulse-backend/config/ca.crt
certfile /home/saniyachavani/Documents/PrecisionpulseDocs/dspl-precision-pulse-backend/config/server.crt
keyfile /home/saniyachavani/Documents/PrecisionpulseDocs/dspl-precision-pulse-backend/config/server.key
require_certificate false
tls_version tlsv1.2

persistence true
persistence_location /tmp/mosquitto-data/
log_dest stdout
