sonar.projectKey=dspl-precision-pulse-desktop
sonar.projectName=PrecisionPulse Desktop
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_4f653a9b5bf7cad9e5d54268f20c04957658b236

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/data/**,**/assets/**
sonar.sourceEncoding=UTF-8
