sonar.projectKey=dspl-precision-pulse-backend
sonar.projectName=PrecisionPulse Backend
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_cf272065f502897ddb5cf489a7f8eeb1ea58b023

sonar.sources=app,config
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=**/.venv/**,**/migrations/**,**/__pycache__/**,**/flask_session/**
sonar.sourceEncoding=UTF-8
